### ISSUE TITLE
dump error

### ISSUE THREAD

**Issue by danwils33** [AdityaChaudhary0005/BitClout.py#1]
with all the json.dump commands I keep getting:

TypeError: dump() missing 1 required positional argument: 'fp'

**Comment by ItsAditya-xyz** [comment]
Thanks for pointing this out @danwils33 . I am stupid actually and forgot to add the file argument in the dump() method.
It's not a problem with the module but a syntax error while using json module.
Updated the readme file!
Make changes in your code and try again :`
for example this code will work as it has the file argument where you want to dump the data
```python
import bitclout
import json
with open("userInfo.json", "w") as file:
    listOfPublicKeys = ["BC1YLjJVhcVAi5UCYZ2aTNwRMtqvzQar4zbymr7fyinu8MsWLx2A1g1"] # you can pass multiple public key of users
    json.dump(bitclout.Users.getUserStateless(listOfPublicKeys), file)
```
